FROM python:3.10.12-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 5000

# Run app.py when the container launches
CMD ["python", "main.py"]

# docker build -t models_api_angels .
# docker run -p 5000:5000 models_api_angels