server:
  port: 8081

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    path match:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:mysql://${DB_ADDRESS}/${DB_NAME}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate.format_sql: true
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
spring doc:
  swagger-ui:
    path: /swagger-ui.html
